version: "3.9"

services:
  pokemon-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
